name: todos_repository
description: A repository that handles todo related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  todos_api:
    path: '../todos_api'

dev_dependencies:
  local_storage_todos_api:
    path: '../local_storage_todos_api'
  mocktail: ^0.3.0
  shared_preferences: ^2.0.15
  test: ^1.19.2
  very_good_analysis: ^3.1.0
